### ISSUE TITLE
Wrong formulas being read from excel (xlsx) file 

### ISSUE THREAD

**Issue by cablegui** [nacnudus/tidyxl#26]
I am using tidyxl version 1.0.1

> > packageVersion("tidyxl")
> [1] ‘1.0.1’

I wanted to read the formulas out from different cells so I loaded the file

`t <- tidyxl::xlsx_cells(path = paste0(file,file_name), sheets=sheetName)`

and pulled out the formula using 

`t[grep(pattern = "^BN3114$", x = t$address,ignore.case = TRUE, value = FALSE),]$formula`

which returns

`"P3114*AN3105*AY3105-AC3105"`

The actual excel file though has the formula as 

`"P3114*AN3114*AY3114-AC3114"`

I noticed that this issue happens if the excel sheet cells are protected.

**Comment by nacnudus** [comment]
Hi @cablegui.  please could you provide a file, and the output you expect.  I'm afraid there is nothing I can do without it!

By the way, here is a simpler way to filter for cell `"BN3114"`.

```r
t[t$address == "BN3114", ]$formula
```

**Comment by cablegui** [comment]
@nacnudus Unfortunately I cannot upload from my office due to security reasons. I will upload a smaller reproducible password protected workbook as soon as I get home.

This is great package by the way.

**Comment by cablegui** [comment]
Here you go. The password to unlock the cells in the sheet is test

One more thing. I noted that after you unlock and only after recalculating every cell the formula reads correctly. 

[Test_book.xlsx](https://github.com/nacnudus/tidyxl/files/1948561/Test_book.xlsx)

```
library(tidyverse)
library(tidyxl)
file_name <- "./Test_book.xlsx"
sheetName <- "Sheet1"
t <- tidyxl::xlsx_cells(path = file_name, sheets=sheetName)
t[t$address == "L10", ]$formula
t[t$address == "L14", ]$formula
```
this returns

> > t[t$address == "L10", ]$formula
> [1] "MAX(0,(E10*F10)-G10)"
> > t[t$address == "L14", ]$formula
> [1] "MAX(0,(E14*F10)-G10)"

**Comment by nacnudus** [comment]
The bug is in the formula parser, which doesn't recognise `*F10` or `-G10` as combination of an operator and a reference.  This might take me a little while to figure out because I can't remember how the parser works, but I'll do my best!

To explain why the formula has to be parsed (reminding myself) when you create a formula by writing one and then dragging down, Excel only writes the first one to the file.  The other formulas must be reconstructed as an offset of the first formula, which means recognising which parts of the formula refer to cell addresses.

**Comment by cablegui** [comment]
Yes it works. I also tried removing the password, adding a new formula row and a new formula column and locking it. It reads the formulas correctly.

**Comment by cablegui** [comment]
I will close the issue if that is ok?

**Comment by nacnudus** [comment]
Thanks!

(fixed in https://github.com/nacnudus/tidyxl/pull/27)
