### ISSUE TITLE
tidyxl::xlsx_cells crashes when reading excel file

### ISSUE THREAD

**Issue by Atan1988** [nacnudus/tidyxl#30]
Hello,

Thank you for this great package. When using tidyxl, I sometimes encounter the situation where xlsx_cells crashes session. I have attached an example that crashes my R session whenever I try to read it using xlsx_cells. 

[test.xlsx](https://github.com/nacnudus/tidyxl/files/1989930/test.xlsx)

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.1.18

**Comment by nacnudus** [comment]
Confirmed.  Thanks for reporting.

**Comment by Jurgaze** [comment]
I realize it's been quite some time, but since I encounter the same problem (R session aborted upon calling xlsx_cells) I thouhgt this might be a good place to report the issue.

File that crashed my session is attached.
[newEXCEL.xlsx](https://github.com/nacnudus/tidyxl/files/5688837/newEXCEL.xlsx)

**Comment by nacnudus** [comment]
@Jurgaze thanks for reporting the issue and checking the existing issues first.

This original bug turns out not to have been related to yours, even though it had the same result (crash), although you couldn't have known that.  Usually it is better to open a new issue than to comment on a closed one, unless you are sure that it is the same thing.  You can of course mention the closed issue in your new issue.
